config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :technicians
  resources :work_orders

  root 'technicians#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/technician.rb
class Technician < ApplicationRecord
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:name, :city)
    end
end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  before_action :set_technician, only: %i[ show edit update destroy ]

  # GET /technicians or /technicians.json
  def index
    @technicians = Technician.all
    @work_orders = WorkOrder.all
    @locations = Location.all
  end

  # GET /technicians/1 or /technicians/1.json
 
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[ show edit update destroy ]

  # GET /work_orders or /work_orders.json
  def index
    @work_orders = WorkOrder.all
  end

  # GET /work_orders/1 or /work_orders/1.json
  def show
  end

  # GET /work_orders/new
  def new
    @work_order = WorkOrder.new
  end

  # GET /work_orders/1/edit
  def edit
  end

  # POST /work_orders or /work_orders.json
  def create
    @work_order = WorkOrder.new(work_order_params)

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to work_order_url(@work_order), notice: "Work order was successfully created." }
        format.json { render :show, status: :created, location: @work_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_orders/1 or /work_orders/1.json
  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to work_order_url(@work_order), notice: "Work order was successfully updated." }
        format.json { render :show, status: :ok, location: @work_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1 or /work_orders/1.json
  def destroy
    @work_order.destroy

    respond_to do |format|
      format.html { redirect_to work_orders_url, notice: "Work order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_order
      @work_order = WorkOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_order_params
      params.require(:work_order).permit(:technician_id, :location_id, :time, :duation, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSchedulingAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>Name:</strong>
    <%= location.name %>
  </p>

  <p>
    <strong>City:</strong>
    <%= location.city %>
  </p>

</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Locations</h1>

<div id="locations">
  <% @locations.each do |location| %>
    <%= render location %>
    <p>
      <%= link_to "Show this location", location %>
    </p>
  <% end %>
</div>

<%= link_to "New location", new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <%= link_to "Edit this location", edit_location_path(@location) %> |
  <%= link_to "Back to locations", locations_path %>

  <%= button_to "Destroy this location", @location, method: :delete %>
</div>

app/views/technicians/_form.html.erb
<%= form_with(model: technician) do |form| %>
  <% if technician.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(technician.errors.count, "error") %> prohibited this technician from being saved:</h2>

      <ul>
        <% technician.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/technicians/_technician.html.erb
<div id="<%= dom_id technician %>">
  <p>
    <strong>Id:</strong>
    <%= technician.id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= technician.name %>
  </p>

</div>

app/views/technicians/edit.html.erb
<h1>Editing technician</h1>

<%= render "form", technician: @technician %>

<br>

<div>
  <%= link_to "Show this technician", @technician %> |
  <%= link_to "Back to technicians", technicians_path %>
</div>

app/views/technicians/index.html.erb
<h1 class="pageTitle">Technician Work Order Scheduling</h1>


<!-- Main div for the entire scheduling grid -->
<div class="scheduleGrid">

	<!-- Creating the left most column displaying the time in hours down the column -->
	<div class="gridLabels"> 
		Time
		<% for i in 0..23 do %>
		<div class="timeColumn">
			<% if i == 0%>
				<%= i + 12 %> am
			<% elsif i > 0 && i < 12 %>
				<%= i %> am
			<% elsif i == 12%>
				<%= i %> pm
			<% else %>
				<%= i - 12 %> pm
			<% end %> 
			
		</div>
		<% end %>

	</div>

	<!-- Creating one column per technician -->
	<% @technicians.each do |technician| %>
	<div class="gridLabels">
		<%= technician.name %>
		<% tempPrevEnd = 102 %>
		<% tempHeight = 0 %>

		<!-- Filtering through the work orders, if the work order matches the correct technician, a work orde rblock is created -->
		<% @work_orders.each do |work_order| %>
			<% if work_order.technician_id == technician.id %>
				<% tempTime = work_order.time.hour * 60 + work_order.time.min + 102 %>  <!-- Creating a temp variable to store the time in an integer format, 102 is added on to align with the corect 60 pixel intervals on the schedule -->
				
				<div class="workOrder<%=work_order.location_id%>" style="height: <%=work_order.duation%>px; top: <%=tempTime%>px"> <!-- Because 1 pixel represents 1 minute, height can be set to duration -->
					<% @locations.each do |location| %>
						<% if location.id == work_order.location_id %> <!-- Ensuring the location id matches the work order location -->

						<!-- Putting the work order information into the work order block -->
						<%= location.name %> 
						(<%= location.city %>) <br>
						<% end %>
					<% end %>
					Start time: 
					<% if work_order.time.hour < 12 %>
						<%=work_order.time.strftime('%H:%M am')%>
					<% elsif work_order.time.hour >= 12 %>
						<%=work_order.time.strftime('%I:%M pm')%>
					<% end %>
					<br>
					Price: $<%= work_order.price %> 
				</div>

				<% tempHeight = tempTime - tempPrevEnd %> <!-- calculating the height of the empty block based on the current work order start tiem and the previous order end time -->
				<div class = "emptyOrder" onclick="timeAlert(<%=tempHeight%>)" style="height: <%=tempHeight%>px; top: <%=tempPrevEnd%>px"> </div>
				<% tempPrevEnd = tempTime + work_order.duation %> <!-- updating previous end time to prepare for next loop iteration --> 
				<% tempHeight = tempTime - tempPrevEnd %> <!-- updating the height for the next empty space -->
			<% end %>
		<% end %>

		<!-- adding in the final open space for the technician - there are no more work orders matchign his ID -->
		<div class = "emptyOrder" onclick = "timeAlert(<%=1550-tempPrevEnd%>)"style="height: <%=1550-tempPrevEnd%>px; top: <%=tempPrevEnd%>px"> </div>
	</div>
	<%end %>
</div>

<!-- Using JavaScript to create a pop up window, used confirm method to mimic real world user deciding to conitnue with this time or cancel and select new block -->
<script type="text/javascript"> 
	function timeAlert(timeVal) {
		if (timeVal < 60){
			confirm("You have "+timeVal+" minutes between your last and next work order")
		}
		else if (timeVal == 60){
			confirm("You have "+(timeVal/60|0)+" hour between your last and next work order")
		}
		else if ((timeVal % 60)==0 && timeVal > 60){
			confirm("You have "+(timeVal/60|0)+" hours between your last and next work order")
		}
		else if ((timeVal % 60)!=0 && timeVal > 60){
			confirm("You have "+(timeVal/60|0)+" hours and "+(timeVal%60)+" minutes between your last and next work order")
		}
	}
</script>

app/views/technicians/new.html.erb
<h1>New technician</h1>

<%= render "form", technician: @technician %>

<br>

<div>
  <%= link_to "Back to technicians", technicians_path %>
</div>

app/views/technicians/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @technician %>

<div>
  <%= link_to "Edit this technician", edit_technician_path(@technician) %> |
  <%= link_to "Back to technicians", technicians_path %>

  <%= button_to "Destroy this technician", @technician, method: :delete %>
</div>

app/views/work_orders/_form.html.erb
<%= form_with(model: work_order) do |form| %>
  <% if work_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
        <% work_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :technician_id, style: "display: block" %>
    <%= form.number_field :technician_id %>
  </div>

  <div>
    <%= form.label :location_id, style: "display: block" %>
    <%= form.number_field :location_id %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.datetime_field :time %>
  </div>

  <div>
    <%= form.label :duation, style: "display: block" %>
    <%= form.number_field :duation %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/work_orders/_work_order.html.erb
<div id="<%= dom_id work_order %>">
  <p>
    <strong>Technician:</strong>
    <%= work_order.technician_id %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= work_order.location_id %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= work_order.time %>
  </p>

  <p>
    <strong>Duation:</strong>
    <%= work_order.duation %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= work_order.price %>
  </p>

</div>

app/views/work_orders/edit.html.erb
<h1>Editing work order</h1>

<%= render "form", work_order: @work_order %>

<br>

<div>
  <%= link_to "Show this work order", @work_order %> |
  <%= link_to "Back to work orders", work_orders_path %>
</div>

app/views/work_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Work orders</h1>

<div id="work_orders">
  <% @work_orders.each do |work_order| %>
    <%= render work_order %>
    <p>
      <%= link_to "Show this work order", work_order %>
    </p>
  <% end %>
</div>

<%= link_to "New work order", new_work_order_path %>

app/views/work_orders/new.html.erb
<h1>New work order</h1>

<%= render "form", work_order: @work_order %>

<br>

<div>
  <%= link_to "Back to work orders", work_orders_path %>
</div>

app/views/work_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @work_order %>

<div>
  <%= link_to "Edit this work order", edit_work_order_path(@work_order) %> |
  <%= link_to "Back to work orders", work_orders_path %>

  <%= button_to "Destroy this work order", @work_order, method: :delete %>
</div>